[project]
name = "desafio-1"
version = "0.1.0"
description = "Aplicação para analisar dependências Python com Snyk e PyPI e gerar um relatório de segurança em Excel"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "packaging>=26.2",
    "pydantic-settings>=2.14.2",
    "requests>=2.34.2",
    "selenium>=4.46.0",
]
